import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { DEMO_USER_ID } from '../config/demo-user.js';
import { loadEnv } from '../config/env.js';
import { createPool } from '../db/pool.js';
import { askForDescriptions } from '../generation/ask.js';
import { EXPERIMENT_PRODUCTS } from '../generation/experiment-products.js';
import { InvalidOutputError } from '../generation/errors.js';
import type { Variants } from '../generation/parse.js';
import { buildPrompt } from '../generation/service.js';
import { complete, type ClientOptions } from '../llm/client.js';
import { readArgs } from './args.js';

// The same products with a cheap and a more capable model, text only, public prompt:
//   pnpm --filter api cost:compare [--models claude-haiku-4-5-20251001,claude-sonnet-5-5:low]
//                                  [--count 10] [--label v2-compare]
// A model can carry its effort after a colon. Sonnet needs it: at the default effort it thinks until
// max_tokens runs out and returns no text at all (see t09-costs.md). Calls are stored in llm_calls
// under the label (cost:report reads them); nothing else is saved. Writes
// docs/experiments/t09-model-comparison.md with empty quality columns to fill in by hand.
const args = readArgs();
const env = loadEnv();
const label = args.label ?? 'v2-compare';
const products = EXPERIMENT_PRODUCTS.slice(0, Number(args.count ?? 10));
const outFile = fileURLToPath(
  new URL('../../../../docs/experiments/t09-model-comparison.md', import.meta.url),
);

const settings = (args.models ?? `${env.LLM_MODEL},claude-sonnet-5-5:low`)
  .split(',')
  .map((spec) => {
    // "model:low" sets the effort, "model:default" leaves it to the API, "model" is for models without effort.
    const [model, level] = spec.split(':') as [string, string | undefined];
    const effort = level === 'default' ? undefined : (level as ClientOptions['effort']);
    // llm_calls has no column for the effort, so it travels in the label: v2-compare-low
    return {
      spec,
      model,
      effort,
      label: level ? `${label}-${level}` : label,
      name: level ? `${model} (effort ${level})` : model,
    };
  });

interface Result {
  variants?: Variants;
  error?: string;
  latencyMs: number;
}

const pool = createPool(env.DATABASE_URL);
const results = new Map<string, Result[]>(settings.map((s) => [s.spec, []]));

try {
  for (const product of products) {
    const { prompt } = await buildPrompt(product, {
      language: env.OUTPUT_LANGUAGE,
      allowPrivatePrompts: false,
      promptLabel: label,
    });

    for (const { spec, model, effort, label: callLabel } of settings) {
      const started = Date.now();
      let measured = 0; // the model's own latency, as llm_calls stores it
      try {
        const { variants } = await askForDescriptions(pool, {
          userId: DEMO_USER_ID,
          model,
          version: 'v2',
          promptLabel: callLabel,
          prompt,
          complete: async (params) => {
            const response = await complete(params, { model, effort });
            measured = response.latencyMs;
            return response;
          },
        });
        results.get(spec)!.push({ variants, latencyMs: measured });
      } catch (error) {
        if (!(error instanceof InvalidOutputError)) throw error;
        results.get(spec)!.push({ error: error.message, latencyMs: Date.now() - started });
      }
      console.log(
        `${product.title.slice(0, 40)} / ${spec}: ${results.get(spec)!.at(-1)!.error ?? 'ok'}`,
      );
    }
  }
} finally {
  await pool.end();
}

const names = settings.map((s) => `\`${s.name}\``);
const lines = [
  '# T09 - Model comparison: the same products with two models',
  '',
  `Generated by \`pnpm --filter api cost:compare\` on ${new Date().toLocaleDateString('sv')}. ${products.length} products, text only, the public \`generate-description.v2\` prompt, language \`${env.OUTPUT_LANGUAGE}\`. Settings: ${names.join(', ')}.`,
  '',
  'Costs, tokens and latency are in [t09-costs.md](t09-costs.md). This file is for the part a script cannot do: **read both versions and give each a score from 1 (unusable) to 5 (publish as it is)**. The score columns are empty on purpose.',
  '',
  `| # | Product | ${names.map((n) => `Score ${n}`).join(' | ')} |`,
  `| --- | --- | ${settings.map(() => '---').join(' | ')} |`,
  ...products.map(
    (p, i) => `| ${i + 1} | ${p.title.slice(0, 60)} | ${settings.map(() => '').join(' | ')} |`,
  ),
  '',
  '## Outputs',
  '',
];
products.forEach((product, i) => {
  lines.push(`### ${i + 1}. ${product.title.slice(0, 80)} (${product.category})`, '');
  for (const { spec, name } of settings) {
    const result = results.get(spec)![i]!;
    lines.push(`**\`${name}\`** (model latency ${Math.round(result.latencyMs)} ms)`, '');
    if (result.error || !result.variants) lines.push(`- Invalid answer: ${result.error}`, '');
    else {
      const { short, medium, seo } = result.variants;
      lines.push(`- **short**: ${short}`, `- **medium**: ${medium}`, `- **seo**: ${seo}`, '');
    }
  }
});
await writeFile(outFile, lines.join('\n'), 'utf8');
console.log(`written ${outFile}`);
