import { PRICES_CHECKED } from '../llm/pricing.js';
import type { Report } from './report.js';

const usd = (n: number, digits = 5) => `$${n.toFixed(digits)}`;
const money = (n: number) =>
  `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const cell = (n: number | null, digits = 5) => (n === null ? '-' : usd(n, digits));
const tokens = (n: number) => Math.round(n).toLocaleString('en-US');
const ms = (n: number) => `${Math.round(n).toLocaleString('en-US')} ms`;
const percent = (n: number) => `${(n * 100).toFixed(1)}%`;

export function renderReport(report: Report, since: string | null, date: string): string {
  const { options: o, rows, without, with: photo, retries, perGeneration, blended } = report;
  const lines: string[] = [];
  const add = (...parts: string[]) => lines.push(...parts);

  add(
    '# T09 - What a description costs',
    '',
    `Generated by \`pnpm --filter api cost:report\` on ${date} from the \`llm_calls\` table. Prices: \`src/llm/pricing.ts\`, checked against the official pricing page on ${PRICES_CHECKED}.`,
    '',
    `**Unit.** One *generation* is one product: the API returns 3 variants (short, medium, SEO) from a single model call. "Cost per description" below means cost per generation; a single variant is a third of it.`,
    '',
    `**Data.** ${rows.used} calls of model \`${o.model}\` with prompt \`${o.prompt}\` (the prompt that is in the repository)${since ? ` made since ${since}` : ''}: ${rows.ok} valid, ${rows.invalid} rejected for format, ${rows.failed} failed before an answer. ${rows.total - rows.used} other calls since then are left out (other models, other settings); they are listed at the end.${since ? ' Calls made before that date are not read at all: some used the private prompt before it was labelled, and their token counts are not comparable.' : ''}`,
    '',
    '## Cost per generation',
    '',
    '| | Without photo | With photo |',
    '| --- | --- | --- |',
    `| Generations measured | ${without.summary.n} | ${photo.summary.n} |`,
    `| Average | ${usd(without.summary.mean)} | ${usd(photo.summary.mean)} |`,
    `| p50 (median) | ${cell(without.summary.p50)} | ${cell(photo.summary.p50)} |`,
    `| p95 | ${cell(without.summary.p95)} | ${cell(photo.summary.p95)} |`,
    `| Average input tokens | ${tokens(without.inputTokens)} | ${tokens(photo.inputTokens)} |`,
    `| Average output tokens | ${tokens(without.outputTokens)} | ${tokens(photo.outputTokens)} |`,
    `| Average model latency | ${ms(without.latencyMs)} | ${ms(photo.latencyMs)} |`,
    '',
    `A photo adds about ${tokens(photo.inputTokens - without.inputTokens)} input tokens (the resized image) and ${usd(photo.summary.mean - without.summary.mean)} per generation. Percentiles use linear interpolation between the closest measurements.`,
    '',
    '## Retries',
    '',
    `Every answer that does not match the schema is stored as \`invalid_output\` and triggers one retry. In this data: **${retries.invalid}** rejected answers (${percent(retries.invalidShare)} of the calls that reached the model), ${usd(retries.wastedSpend)} spent on them. Calls that failed before an answer (rate limit, timeout) are stored with no tokens, so they add nothing to these figures. Spreading that spend over the valid generations multiplies the cost per generation by **${retries.overhead.toFixed(3)}**; the figures below already include it.`,
    '',
    '## Projection',
    '',
    `Cost of the AI calls only, with retries. The blended column assumes the photo share seen in the data (${percent(report.photoShare)} of the generations had a photo).`,
    '',
    '| Generations | Without photo | With photo | Blended |',
    '| --- | --- | --- | --- |',
    ...report.projections.map(
      (p) =>
        `| ${p.generations.toLocaleString('en-US')} | ${money(p.withoutImage)} | ${money(p.withImage)} | ${money(p.blended)} |`,
    ),
    '',
    `Per generation: ${usd(perGeneration.withoutImage)} without photo, ${usd(perGeneration.withImage)} with photo, ${usd(blended)} blended.`,
    '',
    '## Model comparison',
    '',
  );

  if (report.comparison.length === 0) {
    add('No comparison runs found. Run `pnpm --filter api cost:compare`.', '');
  } else {
    add(
      `The same products, text only and the same public prompt, with each model (\`pnpm --filter api cost:compare\`). The outputs side by side, with empty columns for a 1-5 quality score, are in [t09-model-comparison.md](t09-model-comparison.md).`,
      '',
      '| Setting | Calls | Valid | Spent (all calls) | Avg cost per valid generation | Per 1,000 | Avg latency | vs priced model |',
      '| --- | --- | --- | --- | --- | --- | --- | --- |',
      ...report.comparison.map((c) => {
        const ratio = report.costRatios.find((r) => r.setting === c.setting);
        const none = c.valid === 0;
        return `| \`${c.setting}\` | ${c.calls} | ${c.valid} | ${usd(c.spend, 4)} | ${none ? '-' : usd(c.summary.mean)} | ${none ? '-' : money(c.summary.mean * 1000)} | ${none ? '-' : ms(c.latencyMs)} | ${c.label === o.compareLabel && c.model === o.model ? 'baseline' : ratio ? `x${ratio.ratio.toFixed(2)}` : '-'} |`;
      }),
      '',
      'A setting with no valid generation did not produce a usable answer: its calls were paid for and gave nothing. Input tokens differ between models for the same prompt because newer models use a different tokenizer. The quality score is for you to fill in; this report does not judge quality.',
      '',
    );
  }

  add(
    '## Indicative pricing',
    '',
    `**This is an estimate, not a price list.** It answers one question: what would the AI cost be, and what price leaves it at ${percent(1 - o.margin)} of revenue (a ${percent(o.margin)} margin on the AI cost). It uses the blended cost per generation above (${usd(blended)}), so it moves with the photo share, the prompt and the model.`,
    '',
    `| Products per month | AI cost per month | Price for a ${percent(o.margin)} margin on the AI cost |`,
    '| --- | --- | --- |',
    ...report.pricing.map(
      (s) =>
        `| ${s.products.toLocaleString('en-US')} | ${money(s.aiCost)} | ${money(Math.ceil(s.price * 100) / 100)} |`,
    ),
    '',
  );
  if (report.costRatios.length > 0) {
    const [first] = report.costRatios;
    add(
      `With \`${first!.setting}\` instead, the AI cost would be about x${first!.ratio.toFixed(2)} (from the comparison above), and so would the price.`,
      '',
    );
  }
  add(
    'What this estimate leaves out, and why the real price must be higher:',
    '',
    '- Everything that is not the AI call: hosting, database, storage for photos, the domain, monitoring and your time.',
    '- Payment fees (a percentage plus a fixed amount per charge), taxes, refunds and failed payments. At 100 products a month the price above is about one dollar: a fixed fee per charge would take a large share of it, so the AI is not what limits the price there.',
    '- Free trials and users who generate more than the plan assumes. A real plan needs a usage cap, which `GET /api/usage` already measures per month.',
    '- Prices of the provider change; this table is valid for the prices checked on ' +
      PRICES_CHECKED +
      '.',
    '',
    '## Everything in the table',
    '',
    'Every model and prompt combination in `llm_calls`, to show what was left out. `v2-private` rows used the private prompt, which has many more input tokens, and `v1` is the first prompt: neither is comparable with `v2`.',
    '',
    '| Model | Prompt label | Calls | Valid | Avg cost (valid) | Avg input tokens |',
    '| --- | --- | --- | --- | --- | --- |',
    ...report.segments.map(
      (s) =>
        `| \`${s.model}\` | \`${s.prompt}\` | ${s.calls} | ${s.ok} | ${usd(s.avgCost)} | ${tokens(s.avgInput)} |`,
    ),
    '',
  );
  return lines.join('\n');
}
