import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { DEMO_USER_ID } from '../config/demo-user.js';
import { loadEnv } from '../config/env.js';
import { createPool } from '../db/pool.js';
import type { PromptVersion } from './ask.js';
import { InvalidOutputError } from './errors.js';
import { EXPERIMENT_PRODUCTS } from './experiment-products.js';
import { defaultDeps, generateDescriptions } from './service.js';

// Runs every experiment product with v1 and v2 and writes docs/experiments/t05-v1-vs-v2.md.
// Usage: pnpm --filter api gen:compare [--rounds N]   (real calls; every generation is saved to the DB)
const rounds = Number(process.argv[process.argv.indexOf('--rounds') + 1]) || 1;
const outFile = fileURLToPath(
  new URL('../../../../docs/experiments/t05-v1-vs-v2.md', import.meta.url),
);
const VERSIONS: PromptVersion[] = ['v1', 'v2'];

interface Run {
  version: PromptVersion;
  title: string;
  ok: boolean;
  clean: boolean; // no markdown left in the stored text
  attempts: number;
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  latencyMs: number;
  error?: string;
  texts?: string[];
}

const pct = (n: number, total: number) => `${n}/${total} (${Math.round((100 * n) / total)}%)`;
const avg = (values: number[]) => values.reduce((a, b) => a + b, 0) / (values.length || 1);

function summarize(version: PromptVersion, all: Run[]) {
  const list = all.filter((r) => r.version === version);
  const attempts = list.reduce((sum, r) => sum + r.attempts, 0);
  return {
    n: list.length,
    ok: list.filter((r) => r.ok).length,
    clean: list.filter((r) => r.clean).length,
    retries: attempts - list.length,
    avgIn: Math.round(avg(list.map((r) => r.inputTokens))),
    avgOut: Math.round(avg(list.map((r) => r.outputTokens))),
    avgCost: avg(list.map((r) => r.costUsd)),
    avgLatency: Math.round(avg(list.map((r) => r.latencyMs))),
    wasted: list.filter((r) => !r.ok).reduce((sum, r) => sum + r.costUsd, 0),
    failures: list.filter((r) => !r.ok),
  };
}

function report(all: Run[]): string {
  const [v1, v2] = VERSIONS.map((v) => summarize(v, all)) as [
    ReturnType<typeof summarize>,
    ReturnType<typeof summarize>,
  ];
  const usd = (n: number) => `$${n.toFixed(5)}`;
  const row = (label: string, a: string, b: string) => `| ${label} | ${a} | ${b} |`;

  const lines = [
    '# T05 - Prompt v1 (free text) vs v2 (structured output + validation)',
    '',
    `Generated by \`pnpm --filter api gen:compare --rounds ${rounds}\` on ${new Date().toLocaleDateString('sv')}, model \`${loadEnv().LLM_MODEL}\`.`,
    `${EXPERIMENT_PRODUCTS.length} products x ${rounds} round(s), each product run with v1 and v2 in the same session. All numbers come from real calls recorded in \`llm_calls\`.`,
    '',
    '- **v1**: free-text prompt, headings parsed with `indexOf`, no validation, no retry.',
    '- **v2**: JSON schema structured output (`output_config.format`), zod validation with length limits, one retry that tells the model what was wrong.',
    '- "Clean" means the stored descriptions contain no markdown leftovers (`**`, `#` titles, bullets).',
    '',
    '| Metric | v1 | v2 |',
    '| --- | --- | --- |',
    row('Generations', String(v1.n), String(v2.n)),
    row('Parse success rate', pct(v1.ok, v1.n), pct(v2.ok, v2.n)),
    row('Clean result (valid and no markdown leftovers)', pct(v1.clean, v1.n), pct(v2.clean, v2.n)),
    row('Retries (extra model calls)', String(v1.retries), String(v2.retries)),
    row(
      'Avg tokens per generation (in / out)',
      `${v1.avgIn} / ${v1.avgOut}`,
      `${v2.avgIn} / ${v2.avgOut}`,
    ),
    row('Avg cost per generation', usd(v1.avgCost), usd(v2.avgCost)),
    row(
      'Cost per 1,000 generations',
      `$${(v1.avgCost * 1000).toFixed(2)}`,
      `$${(v2.avgCost * 1000).toFixed(2)}`,
    ),
    row('Spent on generations that produced nothing', usd(v1.wasted), usd(v2.wasted)),
    row('Avg model latency per generation', `${v1.avgLatency} ms`, `${v2.avgLatency} ms`),
    '',
  ];

  for (const [name, s] of [
    ['v1', v1],
    ['v2', v2],
  ] as const) {
    if (!s.failures.length) continue;
    lines.push(
      `## ${name} failures`,
      '',
      ...s.failures.map((f) => `- "${f.title.slice(0, 70)}": ${f.error}`),
      '',
    );
  }

  const firstRound = all
    .filter((r) => r.version === 'v2' && r.texts)
    .slice(0, EXPERIMENT_PRODUCTS.length);
  lines.push('## v2 outputs (first round)', '');
  for (const run of firstRound) {
    lines.push(
      `### ${run.title.slice(0, 80)}`,
      '',
      ...(run.texts ?? []).map((t, i) => `- **${['short', 'medium', 'seo'][i]}**: ${t}`),
      '',
    );
  }
  return lines.join('\n');
}

const pool = createPool(loadEnv().DATABASE_URL);
const MARKDOWN = /\*\*|^#+\s|^\s*[-*]\s/m;

// Cost and tokens come from llm_calls, which holds every attempt (also the failed ones).
async function runOnce(version: PromptVersion, product: { title: string; category: string }) {
  const { rows: clock } = await pool.query('SELECT now() AS t');
  const run: Run = {
    version,
    title: product.title,
    ok: false,
    clean: false,
    attempts: 0,
    inputTokens: 0,
    outputTokens: 0,
    costUsd: 0,
    latencyMs: 0,
  };

  try {
    const result = await generateDescriptions(
      pool,
      { userId: DEMO_USER_ID, ...product },
      { ...defaultDeps(), promptVersion: version },
    );
    run.ok = true;
    run.texts = result.descriptions.map((d) => d.content);
    run.clean = run.texts.every((text) => !MARKDOWN.test(text));
  } catch (error) {
    if (!(error instanceof InvalidOutputError)) throw error;
    run.error = error.message;
  }

  const { rows } = await pool.query(
    `SELECT count(*)::int AS attempts, coalesce(sum(input_tokens), 0)::int AS input,
            coalesce(sum(output_tokens), 0)::int AS output, coalesce(sum(cost_usd), 0)::float AS cost,
            coalesce(sum(latency_ms), 0)::int AS latency
     FROM llm_calls WHERE user_id = $1 AND prompt_version = $2 AND created_at >= $3`,
    [DEMO_USER_ID, version, clock[0].t],
  );
  Object.assign(run, {
    attempts: rows[0].attempts,
    inputTokens: rows[0].input,
    outputTokens: rows[0].output,
    costUsd: rows[0].cost,
    latencyMs: rows[0].latency,
  });
  return run;
}

const runs: Run[] = [];
try {
  for (let round = 1; round <= rounds; round++) {
    for (const product of EXPERIMENT_PRODUCTS) {
      for (const version of VERSIONS) {
        const run = await runOnce(version, product);
        runs.push(run);
        console.log(
          `round ${round} ${version} ${run.ok ? 'ok  ' : 'FAIL'} ${product.title.slice(0, 50)}`,
        );
      }
    }
  }
  await writeFile(outFile, report(runs), 'utf8');
  console.log(`\nWritten ${outFile}`);
} finally {
  await pool.end();
}
